### ISSUE TITLE
Device compilation stage of hipcc has ambiguity if `MemoryOrderSeqCst` and `MemoryScopeDevice` are given

### ISSUE THREAD

**Issue by JBludau** [desul/desul#67]
This came up from an issue reported to `Kokkos` [#5299](https://github.com/kokkos/kokkos/issues/5299)
Gist:
When compiling Kokkos with `hipcc` but not enabling the HIP backend the device compilation stage found an ambiguity in `atomic_fetch_add`. But the problem is not tied to Kokkos.

Trigger:
The error is triggered by calling.
```c++
int a;
desul::atomic_fetch_add(a,3,desul::MemoryOrderSeqCst(),desul::MemoryScopeDevice());
```

Problem:
For `MemoryOrderSeqCst` together with `MemoryScopeDevice` there exist two function templates that both would match with deduction of one parameter. I let the compiler unfold the macros here.
```c++
template <class MemoryOrder>
inline __device__ int atomic_fetch_add( int* ptr, int val, MemoryOrder, MemoryScopeDevice) 
{ //fencing and using hipcc shipped atomicAdd with MemoryOrderRelaxed }

template <class T> 
inline __device__ std::enable_if_t<std::is_integral<T>::value, T> 
atomic_fetch_add( T* ptr, T val, MemoryOrderSeqCst order, MemoryScopeDevice scope) 
{// using Impl::atomic_fetch_oper }
```

Other types that suffer the same problem:
This problem exists for `int, unsigned int, unsigned long long` for which the 1st template is generated but also fulfill `is_integral` of the 2nd template. It is true for the following functions `atomic_fetch_` `add,sub,and,or,xor`.

Entry point for the generating macros:
https://github.com/desul/desul/blob/76aee39077079d612ac259551febbc15edf071ef/atomics/include/desul/atomics/HIP.hpp#L98
https://github.com/desul/desul/blob/76aee39077079d612ac259551febbc15edf071ef/atomics/include/desul/atomics/HIP.hpp#L209

Suggested ways forward:

- as there is a refactor by @dalg24 and @crtrott this problem might go away anyways
- be more specific in the `std::enable_if` of the 2nd template. like guarding for `int, unsigned int, unsigned long long` 
- add an abstraction that uses the type as tag for tag dispatch 

I can take care of proposing a pr if we decide on how we want to deal with this

**Comment by trws** [comment]
First blush, this sounds like a bug in our check for compiling with a HIP compiler but without compiling device code.  At the moment we have the `ENABLE_HIP` flag to desul's cmake to compile the backend or not, but we don't store that value to guard the definition of the device functions.  In a case like this, would you have set `ENABLE_HIP` to On or Off?

We should work through the overloads anyway, possibly by overloading the Impl:: layer rather than the outer layer, but if we have a configuration inconsistency we should try to address that too.

**Comment by JBludau** [comment]
`ENABLE_HIP` was not defined, as desul was not configured. Just used used `hipcc` to compile.
Minimal example (only needs the headers):
```c++
#include "desul/atomics.hpp"
int main(){
  int a;
  desul::atomic_add(&a,b,desul::MemoryOrderSeqCst(),desul::MemoryScopeDevice());
  return 0;
}
```
compiled with `hipcc -std=c++14 -I/desul/atomics/include main.cpp -o test`

**Comment by JBludau** [comment]
To me it looks like the guard on the fallback we are using is not correct, as it does not exclude the conditions for which the preferred template function exists. The preferred is the one that relaxes the memory order with fences. Unfortunately, the signature of the function template we are using for calling the specialized versions is of the same priority in the template resolution, thus the ambiguity

**Comment by trws** [comment]
Yeah, I think you're right, we have both problems here.  My preference would be to both:

1. Generate a config.hpp or similar header so we can test if desul was configured for a backend or not, and
2. One of your solutions above, possibly generating instances for specific memory orders since that would disambiguate it.

**Comment by JBludau** [comment]
I guess we can close this with the new design of the atomics ... but did anyone actually test if it still works for corner cases like compiling something for host only with `hipcc`?

**Comment by JBludau** [comment]
I will interpret the silence as a 'No, we did not test but it will become visible anyways if still there', thus closing the issue.
